version: '3.8'

services:
  airflow-webserver:
    image: apache/airflow:2.7.0
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-init
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      # FourKa DB Connection 환경변수
      AIRFLOW_CONN_FOURKA_DB: postgres://${FOURKA_DB_USER}:${FOURKA_DB_PASSWORD}@${FOURKA_DB_HOST}:${FOURKA_DB_PORT}/${FOURKA_DB_NAME}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.0
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-init
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      # FourKa DB Connection 환경변수
      AIRFLOW_CONN_FOURKA_DB: postgres://${FOURKA_DB_USER}:${FOURKA_DB_PASSWORD}@${FOURKA_DB_HOST}:${FOURKA_DB_PORT}/${FOURKA_DB_NAME}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler

  postgres_airflow:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.7.0
    depends_on:
      - postgres_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com
      "

volumes:
  postgres_airflow_data: 