#--------
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
#--------
#apiVersion: v1
#kind: Secret
#metadata:
#  name: airflow-db-secret
#  namespace: airflow
#type: Opaque
#stringData:
#  sql_alchemy_conn: postgresql+psycopg2://airflow:airflow@fourka-postgres-service:5432/airflow
---
#--------
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
  AIRFLOW__CORE__PARALLELISM: "1"
  AIRFLOW__SCHEDULER__MAX_TIS_PER_QUERY: "1"
  AIRFLOW__WEBSERVER__WEB_SERVER_HOST: "0.0.0.0"
  AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8080"
  #AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://vectoruser:pgvectorpassword@pgvector-service.database:5432/airflow_metadata"
  #AIRFLOW_CONN_FOURKA_DB: "postgresql://vectoruser:pgvectorpassword@pgvector-service.database:5432/ai_fastapi_db"
  # Airflow 메타데이터 DB (세션 풀 권장: PgBouncer-RW 또는 HAProxy 5432)
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres:postgressuperuser@pgbouncer-rw.databasecluster.svc.cluster.local:5432/airflow_metadata
  # DAG에서 쓰는 fourka_db 연결 (업데이트/로그 적재 등 쓰기 포함 → RW)
  AIRFLOW_CONN_FOURKA_DB: "postgresql://postgres:postgressuperuser@pgbouncer-rw.databasecluster.svc.cluster.local:5432/ai_db
---
#--------
apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init
  namespace: airflow
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: dykkim01/fourka-airflow-2.7.0-postgres:0.0.1
        envFrom:
        - configMapRef:
            name: airflow-config
        command: ["/bin/bash","-c"]
        args:
          - |
            airflow db init && \
            airflow users create \
              --username admin \
              --password admin \
              --firstname Admin \
              --lastname User \
              --role Admin \
              --email admin@fourka.com
---
#----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - name: airflow-webserver-container
        image: dykkim01/fourka-airflow-2.7.0-postgres:0.0.1
        envFrom:
          - configMapRef:
              name: airflow-config
        env:
          - name: AIRFLOW__WEBSERVER__WEB_SERVER_HOST
            value: "0.0.0.0"
          - name: AIRFLOW__WEBSERVER__WEB_SERVER_PORT
            value: "8080"
          - name: AIRFLOW__WEBSERVER__WORKERS
            value: "1"
          - name: AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT
            value: "300"
          - name: AIRFLOW__API__AUTH_BACKENDS
            value: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
        command: ["airflow","webserver"]
        resources:
          requests: { cpu: "100m", memory: "256Mi" }
          limits:   { cpu: "2", memory: "1Gi" }
---
#--------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler-container
        image: dykkim01/fourka-airflow-2.7.0-postgres:0.0.1
        envFrom:
          - configMapRef:
              name: airflow-config
        resources:
          requests: { cpu: "200m", memory: "512Mi" }
          limits:   { cpu: "500m", memory: "1Gi" }
        command: ["airflow","scheduler"]
---
#---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  selector: { app: airflow-webserver }
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
