"""피드백_사유_선택지_추가

Revision ID: 141e4bcd27d6
Revises: 1506b08622b2
Create Date: 2025-08-07 10:53:42.191168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141e4bcd27d6'
down_revision: Union[str, Sequence[str], None] = '1506b08622b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. FeedbackReason enum 생성
    feedback_reason_enum = sa.Enum('OUTDATED_INFO', 'INTENT_FAILURE', 'WRONG_ANSWER', 'MISSING_INFO', 'OTHER', name='feedbackreason')
    feedback_reason_enum.create(op.get_bind())
    
    # 2. feedback_reason 컬럼 추가
    op.add_column('feedback', sa.Column('feedback_reason', feedback_reason_enum, nullable=True))
    
    # 3. feedback_content를 nullable로 변경
    op.alter_column('feedback', 'feedback_content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    # 4. company_feedback 뷰 업데이트 (feedback_reason 컬럼 추가)
    op.execute("""
        DROP VIEW IF EXISTS company_feedback;
        CREATE OR REPLACE VIEW company_feedback AS
        SELECT 
            f.feedback_id, 
            f.chat_id, 
            f.feedback_type, 
            f.answer, 
            f.feedback_content, 
            f.feedback_reason,
            f.created_at, 
            c.company_id, 
            ch.question, 
            ch.chat_type
        FROM feedback f
        JOIN chat ch ON f.chat_id = ch.chat_id
        JOIN "user" u ON ch.user_id = u.user_id
        JOIN company c ON u.company_id = c.company_id;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. company_feedback 뷰를 원래대로 복원 (feedback_reason 컬럼 제거)
    op.execute("""
        DROP VIEW IF EXISTS company_feedback;
        CREATE OR REPLACE VIEW company_feedback AS
        SELECT 
            f.feedback_id, 
            f.chat_id, 
            f.feedback_type, 
            f.answer, 
            f.feedback_content, 
            f.created_at, 
            c.company_id, 
            ch.question, 
            ch.chat_type
        FROM feedback f
        JOIN chat ch ON f.chat_id = ch.chat_id
        JOIN "user" u ON ch.user_id = u.user_id
        JOIN company c ON u.company_id = c.company_id;
    """)
    
    # 2. feedback_content를 다시 NOT NULL로 변경
    op.alter_column('feedback', 'feedback_content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    # 3. feedback_reason 컬럼 삭제
    op.drop_column('feedback', 'feedback_reason')
    
    # 4. FeedbackReason enum 삭제
    feedback_reason_enum = sa.Enum('OUTDATED_INFO', 'INTENT_FAILURE', 'WRONG_ANSWER', 'MISSING_INFO', 'OTHER', name='feedbackreason')
    feedback_reason_enum.drop(op.get_bind())
    # ### end Alembic commands ###
