"""Feedback[content -> feedback_content] & Chat [message -> question]

Revision ID: 1506b08622b2
Revises: f5b402b5e543
Create Date: 2025-08-06 14:00:28.806977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1506b08622b2'
down_revision: Union[str, Sequence[str], None] = 'f5b402b5e543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 0. View 삭제 (message 컬럼 참조)
    op.execute("DROP VIEW IF EXISTS company_feedback")
    
    # 1. question 컬럼을 nullable=True로 추가
    op.add_column('chat', sa.Column('question', sa.String(), nullable=True))
    
    # 2. message 데이터를 question으로 복사
    op.execute("UPDATE chat SET question = message")
    
    # 3. question 컬럼을 NOT NULL로 변경
    op.alter_column('chat', 'question', nullable=False)
    
    # 4. message 컬럼 삭제
    op.drop_column('chat', 'message')
    
    # 5. feedback_content 컬럼을 nullable=True로 추가
    op.add_column('feedback', sa.Column('feedback_content', sa.String(), nullable=True))
    
    # 6. content 데이터를 feedback_content로 복사
    op.execute("UPDATE feedback SET feedback_content = content")
    
    # 7. feedback_content 컬럼을 NOT NULL로 변경
    op.alter_column('feedback', 'feedback_content', nullable=False)
    
    # 8. 인덱스 삭제
    op.drop_index(op.f('idx_feedback_company_lookup'), table_name='feedback')
    
    # 9. content 컬럼 삭제
    op.drop_column('feedback', 'content')
    
    # 10. View 재생성 (question 컬럼 사용)
    op.execute("""
        CREATE OR REPLACE VIEW company_feedback AS
        SELECT 
            f.feedback_id, f.chat_id, ch.chat_type, ch.question, f.answer, f.feedback_type, f.feedback_content, f.created_at,
            c.company_id, u.user_id, u.name as user_name, c.name as company_name
        FROM feedback f
        JOIN chat ch ON f.chat_id = ch.chat_id
        JOIN "user" u ON ch.user_id = u.user_id
        JOIN company c ON u.company_id = c.company_id;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 0. View 삭제 (question 컬럼 참조)
    op.execute("DROP VIEW IF EXISTS company_feedback")
    
    # 1. content 컬럼을 nullable=True로 추가
    op.add_column('feedback', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # 2. feedback_content 데이터를 content로 복사
    op.execute("UPDATE feedback SET content = feedback_content")
    
    # 3. content 컬럼을 NOT NULL로 변경
    op.alter_column('feedback', 'content', nullable=False)
    
    # 4. 인덱스 생성
    op.create_index(op.f('idx_feedback_company_lookup'), 'feedback', ['feedback_id', 'chat_id'], unique=False)
    
    # 5. feedback_content 컬럼 삭제
    op.drop_column('feedback', 'feedback_content')
    
    # 6. message 컬럼을 nullable=True로 추가
    op.add_column('chat', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # 7. question 데이터를 message로 복사
    op.execute("UPDATE chat SET message = question")
    
    # 8. message 컬럼을 NOT NULL로 변경
    op.alter_column('chat', 'message', nullable=False)
    
    # 9. question 컬럼 삭제
    op.drop_column('chat', 'question')
    
    # 10. View 재생성 (message 컬럼 사용)
    op.execute("""
        DROP VIEW IF EXISTS company_feedback;
    """)
    # ### end Alembic commands ###
