"""create faq_id

Revision ID: 6a08a746d11f
Revises: 9b8841d04bf6
Create Date: 2025-08-11 13:42:29.078048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a08a746d11f'
down_revision: Union[str, Sequence[str], None] = '9b8841d04bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decay_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decay_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('execution_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('chunks_before_decay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunks_after_decay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('affected_chunks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('decay_logs_pkey'))
    )
    # ### end Alembic commands ###
