"""KeywordLog 추가

Revision ID: 9b8841d04bf6
Revises: 141e4bcd27d6
Create Date: 2025-08-08 10:21:03.920078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8841d04bf6'
down_revision: Union[str, Sequence[str], None] = '141e4bcd27d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_keyword_log_company_id'), 'keyword_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_keyword_log_keyword'), 'keyword_log', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_log_keyword'), table_name='keyword_log')
    op.drop_index(op.f('ix_keyword_log_company_id'), table_name='keyword_log')
    op.drop_table('keyword_log')
    # ### end Alembic commands ###
