"""모델 업데이트: Chat chat_type 추가

Revision ID: c15c53307616
Revises: c5629f1a6fea
Create Date: 2025-08-06 11:31:21.300111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15c53307616'
down_revision: Union[str, Sequence[str], None] = 'c5629f1a6fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        DELETE FROM company a 
        USING company b 
        WHERE a.ctid < b.ctid AND a.email = b.email
    """)
    op.create_unique_constraint(None, 'company', ['email'])
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'default@example.com'::character varying"))
    op.create_unique_constraint(None, 'company', ['email'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'user@example.com'::character varying"))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 제약조건 이름을 명시적으로 지정
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user@example.com'::character varying"))
    op.drop_constraint('company_email_key', 'company', type_='unique')
    op.alter_column('company', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'default@example.com'::character varying"))
    # ### end Alembic commands ###
