"""모델 업데이트: Company 필드 추가, User email 추가, UserChatRoom ID 추가

Revision ID: c5629f1a6fea
Revises: 67bb9d002b95
Create Date: 2025-08-04 14:51:34.740405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5629f1a6fea'
down_revision: Union[str, Sequence[str], None] = '67bb9d002b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decay_logs')
    op.add_column('chat', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat_room', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('chunk', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('chunk_doc_id_fkey'), 'chunk', type_='foreignkey')
    op.create_foreign_key(None, 'chunk', 'documents', ['doc_id'], ['doc_id'])
    op.add_column('company', sa.Column('think_level', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('company', sa.Column('speech_level', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('company', sa.Column('email', sa.String(), nullable=True, server_default='default@example.com'))
    op.add_column('company', sa.Column('logo_url', sa.String(), nullable=False, server_default='https://default-logo.com'))
    op.add_column('company', sa.Column('token', sa.String(), nullable=False, server_default='default-token'))
    op.add_column('company', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # UNIQUE 제약 조건은 수동으로 나중에 설정
    # op.create_unique_constraint(None, 'company', ['email'])
    op.add_column('department', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('faq', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('feedback', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('folder', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tag', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(), nullable=True, server_default='user@example.com'))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # UNIQUE 제약 조건은 수동으로 나중에 설정
    # op.create_unique_constraint(None, 'user', ['email'])
    op.add_column('user_chat_room', sa.Column('user_chat_room_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('user_chat_room', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_chat_room', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chat_room', 'updated_at')
    op.drop_column('user_chat_room', 'created_at')
    op.drop_column('user_chat_room', 'user_chat_room_id')
    # UNIQUE 제약 조건 제거 (원래 없었음)
    # op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'email')
    op.drop_column('tag', 'updated_at')
    op.drop_column('folder', 'updated_at')
    op.drop_column('feedback', 'updated_at')
    op.drop_column('faq', 'updated_at')
    op.drop_column('documents', 'updated_at')
    op.drop_column('department', 'updated_at')
    # UNIQUE 제약 조건 제거 (원래 없었음)
    # op.drop_constraint(None, 'company', type_='unique')
    op.drop_column('company', 'updated_at')
    op.drop_column('company', 'token')
    op.drop_column('company', 'logo_url')
    op.drop_column('company', 'email')
    op.drop_column('company', 'speech_level')
    op.drop_column('company', 'think_level')
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.create_foreign_key(op.f('chunk_doc_id_fkey'), 'chunk', 'documents', ['doc_id'], ['doc_id'], ondelete='CASCADE')
    op.alter_column('chunk', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('chat_room', 'updated_at')
    op.drop_column('chat', 'updated_at')
    op.create_table('decay_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('execution_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('chunks_before_decay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunks_after_decay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('affected_chunks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('decay_logs_pkey'))
    )
    # ### end Alembic commands ###
