"""청크 테이블에 가중치 컬럼 추가 및 chat 테이블에 chunk_ids 추가

Revision ID: ef0aa421cbc6
Revises: 83614ee2d40b
Create Date: 2025-07-29 13:32:59.152623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef0aa421cbc6'
down_revision: Union[str, Sequence[str], None] = '83614ee2d40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chunk', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('chunk', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'updated_at')
    op.drop_column('chunk', 'weight')
    op.drop_column('chat', 'chunk_ids')
    # ### end Alembic commands ###
