"""Chat 테이블에 chat_type 필드 추가

Revision ID: f5b402b5e543
Revises: c15c53307616
Create Date: 2025-08-06 11:43:38.345030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b402b5e543'
down_revision: Union[str, Sequence[str], None] = 'c15c53307616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ChatType enum 생성 및 chat_type 컬럼 추가
    chat_type_enum = sa.Enum('FAQ', 'DOC', name='chattype')
    chat_type_enum.create(op.get_bind())
    op.add_column('chat', sa.Column('chat_type', chat_type_enum, nullable=False, server_default='FAQ'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'chat_type')
    # ChatType enum 삭제
    sa.Enum(name='chattype').drop(op.get_bind())
    # ### end Alembic commands ###
